dist: bionic

language: cpp
compiler:
  - clang

git:
  depth: 1

addons:
  apt:
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - boost1.67
      - libssl-dev
      - libmysqlclient-dev
      - libreadline6-dev
      - zlib1g-dev
      - libbz2-dev
      - p7zip-full
      - g++-8

services:
  - mysql

script:
  - rm -rf .git
  - chmod +x release-tdb.sh
  - ./release-tdb.sh
